// File generated by FlutterFire CLI & configured for Life Daily.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTQory719NAnXCcdYYvJvxIUxJFpUWGcQ',
    appId: '1:344724751214:web:48a59cb76c0ecb6375377f',
    messagingSenderId: '344724751214',
    projectId: 'daily-tasks-f9ba1',
    authDomain: 'daily-tasks-f9ba1.firebaseapp.com',
    storageBucket: 'daily-tasks-f9ba1.firebasestorage.app',
    measurementId: 'G-V94S4X7HJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyConbEFDigSXGhbtZb2hfRL5KnPAmJOjtQ',
    appId: '1:344724751214:android:41e6eea93a37686775377f',
    messagingSenderId: '344724751214',
    projectId: 'daily-tasks-f9ba1',
    storageBucket: 'daily-tasks-f9ba1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyConbEFDigSXGhbtZb2hfRL5KnPAmJOjtQ',
    appId: '1:344724751214:ios:41e6eea93a37686775377f',
    messagingSenderId: '344724751214',
    projectId: 'daily-tasks-f9ba1',
    storageBucket: 'daily-tasks-f9ba1.firebasestorage.app',
    iosBundleId: 'com.life_goals_pro.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyConbEFDigSXGhbtZb2hfRL5KnPAmJOjtQ',
    appId: '1:344724751214:ios:41e6eea93a37686775377f',
    messagingSenderId: '344724751214',
    projectId: 'daily-tasks-f9ba1',
    storageBucket: 'daily-tasks-f9ba1.firebasestorage.app',
    iosBundleId: 'com.life_goals_pro.app',
  );
}
