import 'package:life_daily_app/core/constants/locale_keys.dart';

const Map<String, String> arSa = {
  LocaleKeys.appName: 'الحياة اليومية',
  LocaleKeys.homeTitle: 'حياتك في مكان واحد وبهدوء',
  LocaleKeys.homeSubtitle:
      'أهداف، مذكرات، مال، وشغل — بسيط وجاهز من أول ثانية.',
  LocaleKeys.theme: 'المظهر',
  LocaleKeys.language: 'اللغة',
  LocaleKeys.settings: 'الإعدادات',
  LocaleKeys.lightMode: 'فاتح',
  LocaleKeys.darkMode: 'داكن',
  LocaleKeys.themeLight: 'فاتح — سماوي',
  LocaleKeys.themeDark: 'داكن — سماوي',
  LocaleKeys.themeNoirRed: 'أسود وأحمر',
  LocaleKeys.themeSunYellow: 'أبيض وأصفر',
  LocaleKeys.themeBlushPink: 'وردي وأبيض',
  LocaleKeys.english: 'الإنجليزية',
  LocaleKeys.arabic: 'العربية',
  LocaleKeys.preparingSpace: 'نجهّز مساحتك…',
  LocaleKeys.retry: 'حاول مرة أخرى',
  LocaleKeys.saveDataTitle: 'احفظ بياناتك وافتحها من أي مكان',
  LocaleKeys.saveDataSubtitle:
      'ضغطة واحدة. أهدافك ومذكراتك ومالك تفضل معاك على أي موبايل.',
  LocaleKeys.continueGoogle: 'المتابعة مع Google',
  LocaleKeys.continueApple: 'تسجيل الدخول بـ Apple',
  LocaleKeys.dataSaved: 'بياناتك محفوظة. افتحها من أي جهاز.',
  LocaleKeys.goalsTitle: 'الأهداف',
  LocaleKeys.goalsSubtitle: 'اسم، تفاصيل، تاريخ، وفئة حياة',
  LocaleKeys.goalsEmptyTitle: 'ما في أهداف بعد',
  LocaleKeys.goalsEmptyMessage: 'أضف هدف لما تكون جاهز. بدون تعقيد.',
  LocaleKeys.journalTitle: 'المذكرات',
  LocaleKeys.journalSubtitle: 'سطر لليوم',
  LocaleKeys.journalEmptyTitle: 'المذكرة فاضية',
  LocaleKeys.journalEmptyMessage: 'اكتب سطر وقت ما يهمك شيء.',
  LocaleKeys.journalHint: 'سطر لليوم…',
  LocaleKeys.journalSearch: 'دور في المذكرات',
  LocaleKeys.journalToday: 'اليوم',
  LocaleKeys.journalLog: 'السجل',
  LocaleKeys.editJournal: 'تعديل المذكرة',
  LocaleKeys.addJournal: 'مذكرة جديدة',
  LocaleKeys.noteTitle: 'العنوان',
  LocaleKeys.noteDetails: 'التفاصيل',
  LocaleKeys.financeTitle: 'المال',
  LocaleKeys.financeSubtitle: 'مصاريف، أرباح، ديون',
  LocaleKeys.financeEmptyTitle: 'الحساب فاضي',
  LocaleKeys.financeEmptyMessage: 'سجّل مصروف أو ربح في ثواني.',
  LocaleKeys.workTitle: 'الشغل',
  LocaleKeys.workSubtitle: 'مهام ويوم العمل',
  LocaleKeys.workEmptyTitle: 'قائمة الشغل فاضية',
  LocaleKeys.workEmptyMessage: 'خلّي بس اللي محتاج تعمله دلوقتي.',
  LocaleKeys.workHint: 'مهمة جديدة',
  LocaleKeys.workDoneEmptyTitle: 'لسه مفيش منجز',
  LocaleKeys.workDoneEmptyMessage: 'أول ما تخلّص مهمة هتظهر هنا.',
  LocaleKeys.workDoneToday: '@count منجز اليوم',
  LocaleKeys.addWork: 'مهمة جديدة',
  LocaleKeys.editWork: 'تعديل المهمة',
  LocaleKeys.workDetails: 'التفاصيل',
  LocaleKeys.quickAdd: 'أضف بسرعة',
  LocaleKeys.askNameTitle: 'نناديك بإيه؟',
  LocaleKeys.askNameHint: 'اسمك',
  LocaleKeys.askNameSubtitle: 'اسمك بس. هنرحّب بيك فيه كل يوم.',
  LocaleKeys.saveName: 'يلا نبدأ',
  LocaleKeys.maybeLater: 'بعدين',
  LocaleKeys.helloName: 'مرحباً، @name',
  LocaleKeys.helloGuest: 'مرحباً',
  LocaleKeys.homePromo: 'يومك أخف لما كل جزء في حياتك له خطوة واضحة.',
  LocaleKeys.analysisTitle: 'نظرة سريعة',
  LocaleKeys.analysisGoals: '@done من @total مكتمل',
  LocaleKeys.analysisJournal: 'المذكرات',
  LocaleKeys.analysisFinance: 'المال',
  LocaleKeys.analysisWork: 'الشغل',
  LocaleKeys.journalCount: '@count فص',
  LocaleKeys.workOpenCount: '@count مفتوح',
  LocaleKeys.comingSoon: 'قريباً',
  LocaleKeys.goalProgressTitle: 'نسبة تحقيق الأهداف',
  LocaleKeys.goalProgressValue: '@percent٪ مكتمل',
  LocaleKeys.addGoal: 'أضف هدف',
  LocaleKeys.editGoal: 'تعديل الهدف',
  LocaleKeys.goalName: 'اسم الهدف',
  LocaleKeys.goalDetails: 'التفاصيل',
  LocaleKeys.goalDate: 'التاريخ',
  LocaleKeys.goalStartDate: 'من',
  LocaleKeys.goalEndDate: 'إلى',
  LocaleKeys.goalKindOnce: 'لمرة واحدة',
  LocaleKeys.goalKindHabit: 'متابعة يومية',
  LocaleKeys.goalDateRange: '@start – @end',
  LocaleKeys.goalCheckIns: '@done من @total يوم',
  LocaleKeys.goalLogDay: 'سجّل يوم',
  LocaleKeys.goalCategory: 'الفئة',
  LocaleKeys.filterAll: 'الكل',
  LocaleKeys.completeGoal: 'إنهاء',
  LocaleKeys.reopenGoal: 'إعادة فتح',
  LocaleKeys.save: 'حفظ',
  LocaleKeys.categoryCourse: 'كورس',
  LocaleKeys.categoryWork: 'شغل',
  LocaleKeys.categoryRoutine: 'روتين صحي',
  LocaleKeys.categoryNutrition: 'تغذية',
  LocaleKeys.categoryFamily: 'أسرة',
  LocaleKeys.categorySleep: 'نوم صحي',
  LocaleKeys.addExpense: 'أضف مصروف',
  LocaleKeys.addSalary: 'سجّل المرتب',
  LocaleKeys.addCategory: 'قسم جديد',
  LocaleKeys.categoryIcon: 'الأيقونة',
  LocaleKeys.financeAmount: 'المبلغ',
  LocaleKeys.financeNote: 'إيه المصروف؟ (اختياري)',
  LocaleKeys.financeCategory: 'القسم',
  LocaleKeys.financeCategoryName: 'اسم القسم',
  LocaleKeys.financeThisMonth: 'هذا الشهر',
  LocaleKeys.financeIncome: 'داخل',
  LocaleKeys.financeSpent: 'خارج',
  LocaleKeys.financeLeft: 'متبقي',
  LocaleKeys.financeHealthGood: 'وضع كويس',
  LocaleKeys.financeHealthWatch: 'ضيّق شوية',
  LocaleKeys.financeHealthBad: 'تعديت الميزانية',
  LocaleKeys.financeHealthUnknown: 'ابدأ بالمرتب',
  LocaleKeys.financeHealthGoodHint: 'لسه في مساحة هذا الشهر. كمّل بنفس الهدوء.',
  LocaleKeys.financeHealthWatchHint:
      'أغلب فلوس الشهر اتصرفت. خفّف شوية الأيام الجاية.',
  LocaleKeys.financeHealthBadHint:
      'المصروف أكبر من اللي دخل. وقف لحظة وعدّل الأيام الجاية.',
  LocaleKeys.financeHealthUnknownHint:
      'سجّل مرتب الشهر مرة واحدة. بعد كده كل مصروف ليه مكان واضح.',
  LocaleKeys.financeRecent: 'آخر الأنشطة',
  LocaleKeys.financeByCategory: 'حسب القسم',
  LocaleKeys.financeCatFood: 'أكل وشرب',
  LocaleKeys.financeCatOutings: 'خروجات',
  LocaleKeys.financeCatBills: 'فواتير',
  LocaleKeys.financeCatHealth: 'صحة وأدوية',
  LocaleKeys.financeCatTransport: 'مواصلات',
  LocaleKeys.financeSalary: 'مرتب',
  LocaleKeys.financeRemaining: 'متبقي @value',
  LocaleKeys.financeCatSavings: 'تحويش',
  LocaleKeys.financeCatInvest: 'استثمار',
  LocaleKeys.financeCatBonus: 'بونس',
  LocaleKeys.financeCatGift: 'هدية',
  LocaleKeys.financeCatProfit: 'مكسب',
  LocaleKeys.financeCatAssociation: 'قبض جمعية',
  LocaleKeys.financeCatOtherIncome: 'دخل آخر',
  LocaleKeys.financeSavingsTitle: 'حوش فلوسك',
  LocaleKeys.financeSavingsHint:
      'كل ما يدخل فلوس، حوش جزء صغير. نفسك الجاية هتشكرك.',
  LocaleKeys.financeSavingsProgress:
      '@amount متحوش هذا الشهر · @percent% من الدخل',
  LocaleKeys.financeSavingsAction: 'حوّش دلوقتي',
  LocaleKeys.financeRoleSpend: 'مصروف معيشة',
  LocaleKeys.financeRoleAllocate: 'تحويش أو استثمار',
  LocaleKeys.financeAllocated: 'متتحوش',
  LocaleKeys.financeFree: 'متاح للمعيشة',
  LocaleKeys.financeExpectedSalary: 'المرتب المتوقع',
  LocaleKeys.financeSpendBudget: 'ميزانية المصروف',
  LocaleKeys.financeMonthPlan: 'خطة الشهر',
  LocaleKeys.financeSplitTitle: 'فلوس الشهر راحت فين',
  LocaleKeys.financeTrendTitle: 'مصروف المعيشة هذا الشهر',
  LocaleKeys.financeLiving: 'معيشة',
  LocaleKeys.financeCharts: 'رسوم',
  LocaleKeys.financeReports: 'تقرير',
  LocaleKeys.financeExpenses: 'مصروف',
  LocaleKeys.financeToday: 'اليوم',
  LocaleKeys.financeCancel: 'إلغاء',
  LocaleKeys.financeAdd: 'إضافة',
  LocaleKeys.financeMonthlyStats: 'إحصاء الشهر',
  LocaleKeys.financeBudgetTitle: 'ميزانية الشهر',
  LocaleKeys.financePercentLeft: 'متبقي @value%',
  LocaleKeys.financeCompareTitle: 'مقارنة',
  LocaleKeys.financeCompareWeek: 'آخر 7 أيام مقابل الأسبوع قبله',
  LocaleKeys.financeCompareMonth: 'هذا الشهر مقابل الشهر اللي فات',
  LocaleKeys.financeCompareUp: '+@value%',
  LocaleKeys.financeCompareDown: '-@value%',
  LocaleKeys.financeCompareSame: 'نفس القيمة',
  LocaleKeys.financeCompareNew: 'جديد',
  LocaleKeys.viewAll: 'عرض الكل',
  LocaleKeys.goalsRecent: 'آخر الأهداف',
  LocaleKeys.navList: 'قائمة',
  LocaleKeys.navProgress: 'تقدم',
  LocaleKeys.navActivity: 'أنشطة',
  LocaleKeys.navNotes: 'مذكرات',
  LocaleKeys.navOpen: 'مفتوح',
  LocaleKeys.navDone: 'منجز',
  LocaleKeys.navSearch: 'بحث',
  LocaleKeys.navHome: 'الرئيسية',
  LocaleKeys.navFolders: 'فولدرات',
  LocaleKeys.navTasks: 'مهام',
  LocaleKeys.folderGeneral: 'عام',
  LocaleKeys.folderName: 'اسم الفولدر',
  LocaleKeys.addFolder: 'فولدر جديد',
  LocaleKeys.renameFolder: 'تعديل الاسم',
  LocaleKeys.foldersHint: 'اضغط مطول على الفولدر للتعديل',
  LocaleKeys.writeAction: 'اكتب',
  LocaleKeys.weekCardTitle: 'هذا الأسبوع',
  LocaleKeys.weekCardHint: 'شوف ملخص إنجازك',
  LocaleKeys.weekDone: 'منجز',
  LocaleKeys.weekAll: 'الكل',
  LocaleKeys.weekStreak: '@count يوم',
  LocaleKeys.weekNotes: '@count فص',
  LocaleKeys.weekEmpty: 'لسه مفيش حاجة الأسبوع ده',
  LocaleKeys.weekRate: 'نسبة الإنجاز',
  LocaleKeys.delete: 'حذف',
  LocaleKeys.confirmDeleteTitle: 'متأكد من الحذف؟',
  LocaleKeys.confirmDeleteGoal:
      'الهدف هيتشال من قائمتك. مفيش رجوع بعد الخطوة دي.',
  LocaleKeys.confirmDeleteFinance:
      'السجل ده هيتشال من أنشطة الشهر. مفيش رجوع بعد الخطوة دي.',
  LocaleKeys.confirmDeleteJournal:
      'الفص ده هيتشال من المذكرة. مفيش رجوع بعد الخطوة دي.',
  LocaleKeys.confirmDeleteWork:
      'المهمة هتتشال من قائمة الشغل. مفيش رجوع بعد الخطوة دي.',
};
