import 'package:life_daily_app/core/constants/locale_keys.dart';

const Map<String, String> enUs = {
  LocaleKeys.appName: 'Modo',
  LocaleKeys.brandTagline: 'Plan it. Do it. Done.',
  LocaleKeys.financeDayView: 'Daily',
  LocaleKeys.financeMonthView: 'Monthly',
  LocaleKeys.financeNet: 'Net',
  LocaleKeys.financeDayEntries: 'This day',
  LocaleKeys.financeDayEmpty: 'Nothing logged on this day yet.',
  LocaleKeys.financeBackToToday: 'Back to today',
  LocaleKeys.financeLeftToday: 'Left to spend today: @value',
  LocaleKeys.previousWeek: 'Previous week',
  LocaleKeys.nextWeek: 'Next week',
  LocaleKeys.generalTasks: 'General tasks',
  LocaleKeys.whenToday: 'Today',
  LocaleKeys.whenTomorrow: 'Tomorrow',
  LocaleKeys.whenPickDate: 'Pick date',
  LocaleKeys.whenAnytime: 'Anytime',
  LocaleKeys.overdue: 'Overdue',
  LocaleKeys.scheduled: 'Scheduled',
  LocaleKeys.anytime: 'Anytime',
  LocaleKeys.addTypeTask: 'Task',
  LocaleKeys.addTypeMoney: 'Money',
  LocaleKeys.addTypeGoal: 'Goal',
  LocaleKeys.quickAddTaskHint: 'What do you need to do?',
  LocaleKeys.taskSection: 'Section',
  LocaleKeys.allSections: 'All sections',
  LocaleKeys.checklist: 'Checklist',
  LocaleKeys.addChecklistItem: 'Add an item',
  LocaleKeys.noArchived: 'Nothing archived yet',
  LocaleKeys.homeTitle: 'Your life, in one calm place',
  LocaleKeys.homeSubtitle:
      'Goals, notes, money, and work — simple, and ready from the first second.',
  LocaleKeys.theme: 'Appearance',
  LocaleKeys.language: 'Language',
  LocaleKeys.settings: 'Settings',
  LocaleKeys.lightMode: 'Light',
  LocaleKeys.darkMode: 'Dark',
  LocaleKeys.themeLight: 'Light — cyan',
  LocaleKeys.themeDark: 'Dark — cyan',
  LocaleKeys.themeNoirRed: 'Black & red',
  LocaleKeys.themeSunYellow: 'White & yellow',
  LocaleKeys.themeBlushPink: 'Pink & white',
  LocaleKeys.english: 'English',
  LocaleKeys.arabic: 'Arabic',
  LocaleKeys.preparingSpace: 'Opening your space…',
  LocaleKeys.retry: 'Try again',
  LocaleKeys.saveDataTitle: 'Save your data and open it anywhere',
  LocaleKeys.saveDataSubtitle:
      'One tap. Your goals, notes, and money stay with you on any phone.',
  LocaleKeys.continueGoogle: 'Continue with Google',
  LocaleKeys.continueApple: 'Sign in with Apple',
  LocaleKeys.dataSaved: 'Your data is saved. Open it on any device.',
  LocaleKeys.goalsTitle: 'Goals',
  LocaleKeys.goalsSubtitle: 'Name, details, date, and a life area',
  LocaleKeys.goalsEmptyTitle: 'No goals yet',
  LocaleKeys.goalsEmptyMessage: 'Add one when you are ready. Nothing to fill.',
  LocaleKeys.journalTitle: 'Journal',
  LocaleKeys.journalSubtitle: 'A note for today',
  LocaleKeys.journalEmptyTitle: 'Quiet for now',
  LocaleKeys.journalEmptyMessage: 'Write a line whenever something matters.',
  LocaleKeys.journalHint: 'A line for today…',
  LocaleKeys.journalSearch: 'Search notes',
  LocaleKeys.journalToday: 'Today',
  LocaleKeys.journalLog: 'Log',
  LocaleKeys.editJournal: 'Edit note',
  LocaleKeys.addJournal: 'New note',
  LocaleKeys.noteTitle: 'Title',
  LocaleKeys.noteDetails: 'Details',
  LocaleKeys.financeTitle: 'Money',
  LocaleKeys.financeSubtitle: 'Spend, earn, debts',
  LocaleKeys.financeEmptyTitle: 'Money starts empty',
  LocaleKeys.financeEmptyMessage: 'Log a spend or an income in seconds.',
  LocaleKeys.workTitle: 'Work',
  LocaleKeys.workSubtitle: 'Tasks and the day job',
  LocaleKeys.workEmptyTitle: 'Work is clear',
  LocaleKeys.workEmptyMessage: 'Keep only what you need to do next.',
  LocaleKeys.workHint: 'New task',
  LocaleKeys.workDoneEmptyTitle: 'Nothing done yet',
  LocaleKeys.workDoneEmptyMessage: 'Finished tasks will land here.',
  LocaleKeys.workDoneToday: '@count done today',
  LocaleKeys.addWork: 'New task',
  LocaleKeys.editWork: 'Edit task',
  LocaleKeys.workDetails: 'Details',
  LocaleKeys.quickAdd: 'Add',
  LocaleKeys.askNameTitle: 'What should we call you?',
  LocaleKeys.askNameHint: 'Your first name',
  LocaleKeys.askNameSubtitle: 'Just your name. We will use it to greet you.',
  LocaleKeys.saveName: 'Let’s start',
  LocaleKeys.askNameLocked:
      'Your name is saved to your account once and can’t be changed later.',
  LocaleKeys.profileNoEmail: 'No email linked',
  LocaleKeys.dailyReminder: 'Daily reminder',
  LocaleKeys.dailyReminderTime: 'Every day at 9:00 PM',
  LocaleKeys.reminderTitle: 'How was your day, @name?',
  LocaleKeys.reminderBody:
      '@done of @total done today · @open open tasks · goals @percent%',
  LocaleKeys.reminderBodyEmpty: 'Take a minute to check your goals and tasks.',
  LocaleKeys.reminderChannel: 'Daily progress',
  LocaleKeys.helloName: 'Hello, @name',
  LocaleKeys.helloGuest: 'Hello',
  LocaleKeys.homePromo:
      'Your day gets lighter when every area has a clear next step.',
  LocaleKeys.analysisTitle: 'Your snapshot',
  LocaleKeys.analysisGoals: '@done / @total done',
  LocaleKeys.analysisJournal: 'Notes',
  LocaleKeys.analysisFinance: 'Money',
  LocaleKeys.analysisWork: 'Work',
  LocaleKeys.journalCount: '@count notes',
  LocaleKeys.workOpenCount: '@count open',
  LocaleKeys.comingSoon: 'Soon',
  LocaleKeys.goalProgressTitle: 'Goal progress',
  LocaleKeys.goalProgressValue: '@percent% complete',
  LocaleKeys.addGoal: 'Add a goal',
  LocaleKeys.editGoal: 'Edit goal',
  LocaleKeys.goalName: 'Goal name',
  LocaleKeys.goalDetails: 'Details',
  LocaleKeys.goalDate: 'Date',
  LocaleKeys.goalStartDate: 'From',
  LocaleKeys.goalEndDate: 'Until',
  LocaleKeys.goalKindOnce: 'One-time',
  LocaleKeys.goalKindHabit: 'Daily follow-through',
  LocaleKeys.goalDateRange: '@start – @end',
  LocaleKeys.goalCheckIns: '@done / @total days',
  LocaleKeys.goalLogDay: 'Log a day',
  LocaleKeys.goalCategory: 'Life area',
  LocaleKeys.filterAll: 'All',
  LocaleKeys.completeGoal: 'Mark done',
  LocaleKeys.reopenGoal: 'Reopen',
  LocaleKeys.save: 'Save',
  LocaleKeys.categoryCourse: 'Course',
  LocaleKeys.categoryWork: 'Work',
  LocaleKeys.categoryRoutine: 'Healthy routine',
  LocaleKeys.categoryNutrition: 'Nutrition',
  LocaleKeys.categoryFamily: 'Family',
  LocaleKeys.categorySleep: 'Healthy sleep',
  LocaleKeys.addExpense: 'Add a spend',
  LocaleKeys.addSalary: 'Log salary',
  LocaleKeys.addCategory: 'New section',
  LocaleKeys.categoryIcon: 'Icon',
  LocaleKeys.financeAmount: 'Amount',
  LocaleKeys.financeNote: 'What was it? (optional)',
  LocaleKeys.financeCategory: 'Section',
  LocaleKeys.financeCategoryName: 'Section name',
  LocaleKeys.financeThisMonth: 'This month',
  LocaleKeys.financeIncome: 'In',
  LocaleKeys.financeSpent: 'Out',
  LocaleKeys.financeLeft: 'Left',
  LocaleKeys.financeHealthGood: 'Looking good',
  LocaleKeys.financeHealthWatch: 'A bit tight',
  LocaleKeys.financeHealthBad: 'Overspent',
  LocaleKeys.financeHealthUnknown: 'Start with your salary',
  LocaleKeys.financeHealthGoodHint:
      'You still have room this month. Keep the same pace.',
  LocaleKeys.financeHealthWatchHint:
      'Most of this month’s money is already used. Slow down a little.',
  LocaleKeys.financeHealthBadHint:
      'Spending is above what came in. Pause and reset the next days.',
  LocaleKeys.financeHealthUnknownHint:
      'Log this month’s salary once. Then every spend has a clear place.',
  LocaleKeys.financeRecent: 'Latest',
  LocaleKeys.financeByCategory: 'By section',
  LocaleKeys.financeCatFood: 'Food & drinks',
  LocaleKeys.financeCatOutings: 'Outings',
  LocaleKeys.financeCatBills: 'Bills',
  LocaleKeys.financeCatHealth: 'Health & medicine',
  LocaleKeys.financeCatTransport: 'Transport',
  LocaleKeys.financeSalary: 'Salary',
  LocaleKeys.financeRemaining: '@value left',
  LocaleKeys.financeCatSavings: 'Savings',
  LocaleKeys.financeCatInvest: 'Investing',
  LocaleKeys.financeCatBonus: 'Bonus',
  LocaleKeys.financeCatGift: 'Gift',
  LocaleKeys.financeCatProfit: 'Profit',
  LocaleKeys.financeCatAssociation: 'Association payout',
  LocaleKeys.financeCatOtherIncome: 'Other income',
  LocaleKeys.financeSavingsTitle: 'Build your savings',
  LocaleKeys.financeSavingsHint:
      'Move a little aside each time money comes in. Future you will thank you.',
  LocaleKeys.financeSavingsProgress:
      '@amount saved this month · @percent% of income',
  LocaleKeys.financeSavingsAction: 'Add to savings',
  LocaleKeys.financeRoleSpend: 'Living spend',
  LocaleKeys.financeRoleAllocate: 'Save or invest',
  LocaleKeys.financeAllocated: 'Set aside',
  LocaleKeys.financeFree: 'Free to live',
  LocaleKeys.financeExpectedSalary: 'Expected salary',
  LocaleKeys.financeSpendBudget: 'Spend budget',
  LocaleKeys.financeMonthPlan: 'This month’s plan',
  LocaleKeys.financeSplitTitle: 'Where the money went',
  LocaleKeys.financeTrendTitle: 'Living spend this month',
  LocaleKeys.financeLiving: 'Living',
  LocaleKeys.financeCharts: 'Charts',
  LocaleKeys.financeReports: 'Reports',
  LocaleKeys.financeExpenses: 'Expenses',
  LocaleKeys.financeToday: 'Today',
  LocaleKeys.financeCancel: 'Cancel',
  LocaleKeys.financeAdd: 'Add',
  LocaleKeys.financeMonthlyStats: 'Monthly statistics',
  LocaleKeys.financeBudgetTitle: 'Monthly budget',
  LocaleKeys.financePercentLeft: '@value% remaining',
  LocaleKeys.financeCompareTitle: 'Comparison',
  LocaleKeys.financeCompareWeek: 'Last 7 days vs previous week',
  LocaleKeys.financeCompareMonth: 'This month vs last month',
  LocaleKeys.financeCompareUp: '+@value%',
  LocaleKeys.financeCompareDown: '-@value%',
  LocaleKeys.financeCompareSame: 'Same',
  LocaleKeys.financeCompareNew: 'New',
  LocaleKeys.viewAll: 'View all',
  LocaleKeys.goalsRecent: 'Recent goals',
  LocaleKeys.navList: 'List',
  LocaleKeys.navProgress: 'Progress',
  LocaleKeys.navActivity: 'Activities',
  LocaleKeys.navNotes: 'Notes',
  LocaleKeys.navOpen: 'Open',
  LocaleKeys.navDone: 'Done',
  LocaleKeys.navSearch: 'Search',
  LocaleKeys.navHome: 'Home',
  LocaleKeys.navFolders: 'Folders',
  LocaleKeys.navTasks: 'Tasks',
  LocaleKeys.folderGeneral: 'General',
  LocaleKeys.folderName: 'Folder name',
  LocaleKeys.addFolder: 'New folder',
  LocaleKeys.renameFolder: 'Rename folder',
  LocaleKeys.foldersHint: 'Long press a folder to rename it',
  LocaleKeys.writeAction: 'Write',
  LocaleKeys.weekCardTitle: 'This week',
  LocaleKeys.weekCardHint: 'See a short summary of your week',
  LocaleKeys.weekDone: 'Done',
  LocaleKeys.weekAll: 'All',
  LocaleKeys.weekStreak: '@count days',
  LocaleKeys.weekNotes: '@count notes',
  LocaleKeys.weekEmpty: 'Nothing logged this week yet',
  LocaleKeys.weekRate: 'Completion',
  LocaleKeys.delete: 'Delete',
  LocaleKeys.confirmDeleteTitle: 'Delete this?',
  LocaleKeys.confirmDeleteGoal:
      'This goal will be removed from your list. You can’t undo this.',
  LocaleKeys.confirmDeleteFinance:
      'This money record will be removed from the month. You can’t undo this.',
  LocaleKeys.confirmDeleteJournal:
      'This note will be removed from your journal. You can’t undo this.',
  LocaleKeys.confirmDeleteWork:
      'This task will be removed from work. You can’t undo this.',

  // Auth Dialog & Status
  LocaleKeys.authTitle: 'Account & Sync',
  LocaleKeys.authSubtitle: 'Sign in to access your data safely on any device',
  LocaleKeys.signIn: 'Sign In',
  LocaleKeys.signUp: 'Create Account',
  LocaleKeys.email: 'Email',
  LocaleKeys.password: 'Password',
  LocaleKeys.forgotPassword: 'Forgot password?',
  LocaleKeys.resetPassword: 'Reset Password',
  LocaleKeys.sendResetLink: 'Send Reset Link',
  LocaleKeys.resetLinkSent: 'Reset link sent to your email.',
  LocaleKeys.noAccount: "Don't have an account? Sign up",
  LocaleKeys.alreadyHaveAccount: 'Already have an account? Sign in',
  LocaleKeys.signOut: 'Sign Out',
  LocaleKeys.signOutTitle: 'Sign out?',
  LocaleKeys.signOutMessage:
      'Your data stays saved in your account. Sign in again to see it.',
  LocaleKeys.signedInAs: 'Signed in as @email',
  LocaleKeys.cloudSync: 'Cloud Sync',
  LocaleKeys.syncStatusSynced: 'Backed up to cloud',
  LocaleKeys.syncStatusGuest: 'Local only (Guest)',
  LocaleKeys.orDivider: 'OR',
  LocaleKeys.invalidEmail: 'Please enter a valid email address.',
  LocaleKeys.passwordTooShort: 'Password must be at least 6 characters.',

  // Goals Action Plan & Trackers
  LocaleKeys.actionPlan: 'Action Plan',
  LocaleKeys.actionPlanSubtitle: 'Check off steps towards achieving your goal',
  LocaleKeys.addTask: 'Add step',
  LocaleKeys.taskTitle: 'Step title',
  LocaleKeys.noTasksYet: 'No action steps added yet.',
  LocaleKeys.trackers: 'Interactive Trackers',
  LocaleKeys.addTracker: 'Add Tracker',
  LocaleKeys.trackerKindNumeric: 'Numeric Target',
  LocaleKeys.trackerKindMilestone: 'Milestones',
  LocaleKeys.trackerKindStreak: 'Streak Counter',
  LocaleKeys.trackerCurrent: 'Current',
  LocaleKeys.trackerTarget: 'Target',
  LocaleKeys.trackerUnit: 'Unit (e.g. pages, km)',
  LocaleKeys.trackerUpdate: 'Update Tracker',
  LocaleKeys.goalOverallProgress: 'Overall Goal Progress',
  LocaleKeys.goalTasksProgress: 'Steps Completed',
  LocaleKeys.viewGoalDetail: 'View Details',
  LocaleKeys.goalDetailTitle: 'Goal Details',

  // Finance Commitments
  LocaleKeys.financeCommitments: 'Monthly Commitments',
  LocaleKeys.financeCommitmentsSubtitle:
      'Bills, rent, loans, and recurring dues',
  LocaleKeys.financeAddCommitment: 'Add Commitment',
  LocaleKeys.financeCommitmentTitle: 'Commitment Title',
  LocaleKeys.financeDueDay: 'Due Day (1-31)',
  LocaleKeys.financeSafeLiquidity: 'Safe Liquidity',
  LocaleKeys.financeSafeLiquidityHint:
      'Income minus spent & remaining unpaid dues',
  LocaleKeys.financePaidCommitments: 'Paid Dues',
  LocaleKeys.financeUnpaidCommitments: 'Pending Dues',
  LocaleKeys.financeMarkPaid: 'Mark Paid',
  LocaleKeys.financeMarkUnpaid: 'Mark Unpaid',

  // Web Shell
  LocaleKeys.webNavGoals: 'Goals',
  LocaleKeys.webNavFinance: 'Money',
  LocaleKeys.webNavSettings: 'Preferences & Cloud',

  // Goal & Task Status
  LocaleKeys.statusNotStarted: 'Not Started',
  LocaleKeys.statusInProgress: 'In Progress',
  LocaleKeys.statusDone: 'Done',
  LocaleKeys.statusArchived: 'Archived',
  LocaleKeys.statusAll: 'All Statuses',
  LocaleKeys.kanbanBoard: 'Board',
  LocaleKeys.dragGoalHere: 'Drag goals here',
  LocaleKeys.changeStatus: 'Change status',
  LocaleKeys.navBoard: 'Board',
  LocaleKeys.taskStatusTodo: 'To Do',
  LocaleKeys.taskStatusPending: 'Pending',
  LocaleKeys.taskStatusInProgress: 'In Progress',
  LocaleKeys.taskStatusDone: 'Done',
  LocaleKeys.statusSectionTodo: 'To-do',
  LocaleKeys.statusSectionInProgress: 'In Progress',
  LocaleKeys.statusSectionComplete: 'Complete',
  LocaleKeys.selectStatus: 'Select Status',
  LocaleKeys.priorityLabel: 'Priority',
  LocaleKeys.priorityUrgent: 'Urgent',
  LocaleKeys.priorityHigh: 'High',
  LocaleKeys.priorityMedium: 'Medium',
  LocaleKeys.priorityLow: 'Low',
  LocaleKeys.priorityNone: 'No Priority',
  LocaleKeys.selectPriority: 'Select Priority',
  LocaleKeys.changePriority: 'Change Priority',
  LocaleKeys.connectedGoal: 'Connected Goal',
  LocaleKeys.reassignGoal: 'Move to Goal',
  LocaleKeys.selectConnectedGoal: 'Select connected goal for task',
  LocaleKeys.prioritySectionUrgent: 'Urgent & Critical',
  LocaleKeys.prioritySectionHigh: 'High Priority',
  LocaleKeys.prioritySectionStandard: 'Standard & Low Priority',
  LocaleKeys.tasksCount: 'Tasks',
  // Login Page Subtitles
  LocaleKeys.signInSubtitle: 'Sign in to access your goals from anywhere',
  LocaleKeys.signUpSubtitle:
      'Create your account and start organizing your life',
  LocaleKeys.resetPasswordSubtitle:
      'Enter your email and we\'ll send a reset link',
  // Team Collaboration
  LocaleKeys.teamMembers: 'Team Members',
  LocaleKeys.invitePartner: 'Invite Partner',
  LocaleKeys.inviteByEmail: 'Invite by Email',
  LocaleKeys.inviteEmailHint: 'Enter the person\'s email address',
  LocaleKeys.sendInvite: 'Send Invite',
  LocaleKeys.inviteSent: 'Invitation sent successfully',
  LocaleKeys.inviteError: 'Failed to send invitation',
  LocaleKeys.pendingInvites: 'Pending Invites',
  LocaleKeys.inviteFrom: 'Invite from @{name}',
  LocaleKeys.inviteToGoal: 'to join goal: @{goal}',
  LocaleKeys.acceptInvite: 'Accept',
  LocaleKeys.declineInvite: 'Decline',
  LocaleKeys.roleOwner: 'Owner',
  LocaleKeys.rolePartner: 'Partner',
  LocaleKeys.noMembersYet: 'No members yet',
  // Task Assignment
  LocaleKeys.assignTo: 'Assign to',
  LocaleKeys.assignedTo: 'Assigned to',
  LocaleKeys.unassigned: 'Unassigned',
  LocaleKeys.changeAssignee: 'Change Assignee',
  LocaleKeys.selectAssignee: 'Select assignee',
  LocaleKeys.cancel: 'Cancel',

  // Daily Tracking Hub & Board
  LocaleKeys.todayTitle: 'My day',
  LocaleKeys.todayHabitsTasksCount: '@{completed} of @{total} completed today',
  LocaleKeys.todayHabits: 'Habits',
  LocaleKeys.todayTasks: 'Tasks',
  LocaleKeys.todayFinance: 'Today\'s Finance',
  LocaleKeys.todayCompleted: 'Completed Today',
  LocaleKeys.habitEveryDay: 'Every day',
  LocaleKeys.habitDaysPerWeek: '@{days} days a week',
  LocaleKeys.spendToday: 'Spent Today',
  LocaleKeys.dailySafeLimit: 'Daily Safe Limit',
  LocaleKeys.commitmentsDueToday: 'Commitments Due Today',
  LocaleKeys.upcomingCommitments: 'Upcoming Commitments',
  LocaleKeys.paidCommitments: 'Paid Commitments',
  LocaleKeys.quickAddExpense: 'Quick Expense',
  LocaleKeys.quickAddIncome: 'Quick Income',
  LocaleKeys.myDay: 'My day',
  LocaleKeys.next7Days: 'Next 7 days',
  LocaleKeys.allMyTasks: 'All my tasks',
  LocaleKeys.taskBoard: 'Tasks',
  LocaleKeys.addSection: 'Add section',
  LocaleKeys.allTasks: 'All Tasks',
  LocaleKeys.selectGoal: 'Select Goal',
  LocaleKeys.noHabitsToday: 'No habits scheduled for today',
  LocaleKeys.noTasksToday: 'No tasks scheduled for today',
};
